{{- with .Values.clusterSeed }}
apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  serviceAccountRef: {{ .serviceAccountRef }}
  templateProcessorImage: {{ .templateProcessorImage }}
  resourceHandlingMode: Apply
  resourceDeletionMode: Delete
  triggers:
  - type: Change
  - type: Periodic
    cron: {{ .triggers.cron | quote }}
  templateSource:
  {{- if $.Values.overwrite.uri }}
    uri: {{ $.Values.overwrite.uri }}
  {{- else }}
    uri: {{ .templateSource.uri }}
  {{- end }}
  {{- if $.Values.overwrite.ref }}
    ref: {{ $.Values.overwrite.ref }}
  {{- else }}
    ref: {{ .templateSource.ref }}
  {{- end }}
    contextDir: {{ .templateSource.contextDir }}
    #secretName: {{ .parameterSource.secretName }}
  parameterSource:
  {{- if $.Values.overwrite.uri }}
    uri: {{ $.Values.overwrite.uri }}
  {{- else }}
    uri: {{ .parameterSource.uri }}
  {{- end }}
  {{- if $.Values.overwrite.ref }}
    ref: {{ $.Values.overwrite.ref }}
  {{- else }}
    ref: {{ .parameterSource.ref }}
  {{- end }}
    contextDir: {{ .parameterSource.contextDir }}
    #secretName: {{ .parameterSource.secretName }}
---
{{- end }}
