# role binding for the operator
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.eunomiaOperator.serviceAccount }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.eunomiaOperator.serviceAccount }}
  namespace: {{ .Values.eunomiaOperator.namespace }}
roleRef:
  kind: ClusterRole
  name: eunomia-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.eunomiaOperator.serviceAccount }}
  namespace: {{ .Values.eunomiaOperator.namespace }}
subjects: 
- kind: ServiceAccount
  name: {{ .Values.eunomiaOperator.serviceAccount }}
  namespace: {{ .Values.eunomiaOperator.namespace }}
roleRef:
  kind: Role
  name: eunomia-operator
  apiGroup: rbac.authorization.k8s.io
---
