{{- range .Values.teams }}
{{- $serviceAccountRef := .serviceAccountRef -}}
{{- $seedNamespace := .seedNamespace -}}
{{- range .namespaces }}
# Service accounts for seed namesapces
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .namespace }}"
spec:
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $serviceAccountRef }}"
  namespace: "{{ .namespace }}"
subjects: 
- kind: ServiceAccount
  name: "{{ $serviceAccountRef }}"
  namespace: "{{ $seedNamespace }}"
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io  
---
# Service accounts for app namespaces
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountRef }}
  namespace: {{ .namespace }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $serviceAccountRef }}"
  namespace: "{{ .namespace }}"
subjects: 
- kind: ServiceAccount
  name: "{{ $serviceAccountRef }}"
  namespace: "{{ .namespace }}"
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io  
---
{{- end }}
{{- end }}
