apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitopsconfig-viewer
rules:
# Allow viewing and listing of gitopsconfigs
- apiGroups:
  - eunomia.kohls.io
  resources:
  - gitopsconfigs
  verbs:
  - get
  - list
  - watch
