# service account for the operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eunomia-operator
  namespace: {{ .Values.namespace }}
---
{{- if .Values.executeClusterAdminTasks }}
# role binding for the operator
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceAccount }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: eunomia-operator
  apiGroup: rbac.authorization.k8s.io
{{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Values.namespace }}
subjects: 
- kind: ServiceAccount
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: eunomia-operator
  apiGroup: rbac.authorization.k8s.io
---
