apiVersion: v1
kind: ServiceAccount
metadata:
  name: eunomia-runner
  namespace: eunomia-hello-world-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eunomia-demo-runner-namespace-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: eunomia-runner
  namespace: eunomia-hello-world-demo
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eunomia-demo-runner-cluster-admin
subjects:
- kind: ServiceAccount
  name: eunomia-runner
  namespace: eunomia-hello-world-demo
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
