apiVersion: v1
kind: ServiceAccount
metadata:
  name: eunomia-runner-yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eunomia-runner-yaml-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: eunomia-runner-yaml
  namespace: eunomia-hello-world-yaml-demo
