apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: hello-world-yaml
spec:
  templateSource:
    uri: https://github.com/Smiley73/eunomia
    ref: demo
    contextDir: examples/hello-world-yaml/templates
  parameterSource:
    contextDir: examples/hello-world-yaml/parameters
  triggers:
  - type: Change
  - type: Webhook
    secret: ciao
  - type: Periodic
    cron: "*/1 * * * *"
  serviceAccountRef: gitops
  templateProcessorImage: quay.io/kohlstechnology/eunomia-base:v0.0.1
  resourceHandlingMode: CreateOrMerge
  resourceDeletionMode: Delete
