apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitopsconfig-admin
rules:
# Allow all actions on gitopsconfigs
- apiGroups:
  - 'eunomia.kohls.io'
  resources:
  - 'gitopsconfigs'
  verbs:
  - '*'
