apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitopsconfig-viewer
  labels:
    # Add these permissions to the "view" and "edit" default roles
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
# Allow viewing and listing of gitopsconfigs
- apiGroups:
  - eunomia.kohls.io
  resources:
  - gitopsconfigs
  verbs:
  - get
  - list
  - watch
