{{- range .Values }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eunomia-operator
subjects:
- kind: ServiceAccount
  name: "{{ .serviceAccountRef }}"
  namespace: "{{ .namespace }}"
roleRef:
  kind: ClusterRole
  name: eunomia-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eunomia-operator
subjects: 
- kind: ServiceAccount
  name: "{{ .serviceAccountRef }}"
  namespace: "{{ .namespace }}"
roleRef:
  kind: Role
  name: eunomia-operator
  apiGroup: rbac.authorization.k8s.io  
---
{{- end }}
