{{- if not .Values.eunomia.operator.deployment.nsRbacOnly -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eunomia-operator
rules:
# needed by operator logic to manage the runners
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'
# needed by operator logic when handling finalizers
- apiGroups:
  - ''
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch  # needed by k8s.io/client-go/tools/cache
# needed by operator to be able to emit events
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
# operator's resources
- apiGroups:
  - eunomia.kohls.io
  resources:
  - '*'
  verbs:
  - '*'
{{- if .Values.eunomia.operator.openshift.enabled }}
- apiGroups:
  - template.openshift.io
  resources:
  - processedtemplates
  verbs:
  - '*'
{{- end }}
{{- end }}
