{{- with .Values.eunomia.operator }}
{{- if not (or .deployment.nsRbacOnly .deployment.operatorHub) -}}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ''
  name: {{ .namespace }}
spec:
{{- end }}
{{- end }}
