{{- with .Values.eunomia.operator }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8383'
  name: eunomia-operator
  namespace: "{{ .namespace }}"
spec:
  selector:
    name: eunomia-operator
  ports:
  - name: webhook
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
{{- end }}
