{{- with .Values.eunomia.operator }}
# service account for the operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eunomia-operator
  namespace: {{ .namespace }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .serviceAccount }}
  namespace: {{ .namespace }}
subjects: 
- kind: ServiceAccount
  name: {{ .serviceAccount }}
  namespace: {{ .namespace }}
roleRef:
  kind: Role
  name: eunomia-operator
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
