FROM @REPOSITORY@/eunomia-base:@IMAGE_TAG@

ENV OC_VERSION=4.7.41

USER root
RUN curl -O https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/${OC_VERSION}/openshift-client-linux.tar.gz && \
    tar --directory /usr/bin -zxvf openshift-client-linux.tar.gz oc

COPY bin/processTemplates.sh /usr/local/bin/processTemplates.sh

USER ${USER_UID}
