FROM @REPOSITORY@/eunomia-base:@IMAGE_TAG@

ENV OC_VERSION=3.11.170

USER root
RUN curl -O http://mirror.openshift.com/pub/openshift-v3/clients/${OC_VERSION}/linux/oc.tar.gz \
  && tar --directory /usr/bin -zxvf oc.tar.gz oc

COPY bin/processTemplates.sh /usr/local/bin/processTemplates.sh

USER ${USER_UID}
