FROM @REPOSITORY@/eunomia-base:@IMAGE_TAG@

ENV OC_VERSION=4.6

USER root
RUN curl -O http://mirror.openshift.com/pub/openshift-v4/clients/oc/${OC_VERSION}/linux/oc.tar.gz && \
    tar --directory /usr/bin -zxvf oc.tar.gz oc

COPY bin/processTemplates.sh /usr/local/bin/processTemplates.sh

USER ${USER_UID}
