apiVersion: apps/v1
kind: Deployment
metadata:
  name: eunomia-operator
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: eunomia-operator
  template:
    metadata:
      labels:
        name: eunomia-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: eunomia-operator
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "eunomia-operator"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
