apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eunomia-operator
rules:
# needed by operator logic  
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'  
# operator's resources  
- apiGroups:
  - eunomia.kohls.io
  resources:
  - '*'
  verbs:
  - '*'
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eunomia-operator
rules:
# leader election   
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - "*"  
#Metrics  
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - "*"
#Metrics  
- apiGroups:
  - "apps"
  resources:
  - replicasets
  - deployments
  verbs: 
  - "get"
  - "list"
# Metrics  
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
# Metrics  
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - eunomia-operator
  verbs:
  - "update"

