apiVersion: v1
kind: Template
metadata:
  labels:
    app: helloworld
  name: helloworld
  namespace: test-eunomia-operator
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: helloworld
  spec:
    serviceAccount: gitops-operator
    serviceAccountName: gitops-operator
    containers:
    - image: quay.io/KohlsTechnology/helloworld:v0.1.0
      imagePullPolicy: Always
      name: helloworld
      ports:
      - containerPort: 8080
        protocol: TCP
      - containerPort: 8888
        protocol: TCP
