FROM @REPOSITORY@/eunomia-helm:@IMAGE_TAG@

ENV OC_VERSION="3.11.165" \
    kubectl=oc

USER root

RUN curl -L http://mirror.openshift.com/pub/openshift-v3/clients/${OC_VERSION}/linux/oc.tar.gz | \
  tar --directory /usr/bin -zxv oc

USER ${USER_UID}
