{{- with .Values.eunomia.operator }}
{{- if .openshift.route.enabled -}}
apiVersion: v1
kind: Route
metadata:
  name: eunomia-operator
  namespace: "{{ .namespace }}"
spec:
  port:
    targetPort: webhook  
  to:
    kind: Service
    name: eunomia-operator
{{- end }}
{{- end }}
