apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: simple-test
  namespace: gitops-operator
spec:
  # Add fields here
  templateSource:
    uri: https://github.com/KohlsTechnology/eunomia
    ref: master
    contextDir: examples/simple/templates
  parameterSource:
    contextDir: examples/simple/parameters
  triggers:
  - type: Change
  - type: Webhook
    secret: ciao
  - type: Periodic
    cron: "0 * * * *"
  serviceAccountRef: gitops
  templateProcessorImage: quay.io/kohlstechnology/eunomia-ocp-templates:latest
  resourceHandlingMode: CreateOrMerge
  resourceDeletionMode: Delete
