{{- range .Values.namespaces }}
apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: "gitopscfg"
  namespace: "{{ .name }}"
spec:
  serviceAccountRef: "{{ $.Values.GitOpsConfig.serviceAccountRef }}"
  templateProcessorImage: "{{ $.Values.GitOpsConfig.templateProcessorImage }}"
  resourceHandlingMode: CreateOrMerge
  resourceDeletionMode: Delete
  triggers:
  - type: Change
  - type: Periodic
    cron: "{{ $.Values.GitOpsConfig.triggers.cron }}"
  templateSource:
{{- if $.Values.overwrite.uri }}
    uri: {{ $.Values.overwrite.uri }}
{{- else }}
    uri: {{ $.Values.GitOpsConfig.templateSource.uri }}
{{- end }}
{{- if $.Values.overwrite.uri }}
    ref: {{ $.Values.overwrite.ref }}
{{- else }}
    ref: {{ $.Values.GitOpsConfig.templateSource.ref }}
{{- end }}
    contextDir: "{{ .templatePath }}"
    #secretName: "{{ $.Values.GitOpsConfig.parameterSource.secretName }}
  parameterSource:
{{- if $.Values.overwrite.uri }}
    uri: {{ $.Values.overwrite.uri }}
{{- else }}
    uri: {{ $.Values.GitOpsConfig.parameterSource.uri }}
{{- end }}
{{- if $.Values.overwrite.uri }}
    ref: {{ $.Values.overwrite.ref }}
{{- else }}
    ref: {{ $.Values.GitOpsConfig.parameterSource.ref }}
{{- end }}
    contextDir: "{{ .parameterPath }}"
    #secretName: "{{ $.Values.GitOpsConfig.parameterSource.secretName }}
---
{{- end }}
